#:schema ../../node_modules/wrangler/config-schema.json
name = "app-router"
main = "out.mjs"
# main = ".open-next/server-functions/default/index.mjs"
compatibility_date = "2024-07-01"
compatibility_flags = ["experimental:nodejs_compat_v2"]
workers_dev = false
minify = false

[vars]
DEBUG = "next:*"
